import { Button, TextEdit, GridBox } from "std-widgets.slint";

component Button inherits Rectangle {
	in-out property text <=> txt.text;
	callback clicked <=> touch.clicked;
	border-width: 0.5px;
	border-color: root.background.darker(25%);
	background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c :  #456;
	width: 120px;
	height: 100px;
	txt := Text {
		x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
		y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
		color: touch.pressed ? #fff : #eee;
	}
	touch := TouchArea { }
}

export component AppWindow inherits Window {
	title: "Calculator";
	in-out property<string> textarea: ""; // Proprietate pentru afișarea textului în zona de text
	callback add_to_text_area(string, string); // Callback pentru adăugarea textului în zona de text
	background: #00FF;
	GridLayout {

		// TASK: Creează un TextEdit pentru zona de text a calculatorului.
		// HINT: Setează lățimea la 600px și înălțimea la 200px.
		text_box := TextEdit {
			font-size: 36px;
			width: 600px;
			height: 200px;
			text: textarea; // Leagă `textarea` la textul afișat în acest `TextEdit`
		}

		GridLayout {

			row: 1;

		   Button {
			text: "1";
			clicked => {
				add_to_text_area(text-box.text, "1");
			}
		   }
		   Button {
			text: "2";
			clicked => {
				add_to_text_area(text-box.text, "2");
			}
		   }
		   Button {
			text: "3";
			clicked => {
				add_to_text_area(text-box.text, "3");
			}
		   }
		   Button {
			text: "+";
			clicked => {
				add_to_text_area(text-box.text, "+");
			}
		   }
		   Button {
			text: "-";
			clicked => {
				add_to_text_area(text-box.text, "-");
			}
		   }
		}

		GridLayout {

			row: 2;

			Button {
				text: "4";
				clicked => {
					add_to_text_area(text-box.text, "4");
				}
			   }
			   Button {
				text: "5";
				clicked => {
					add_to_text_area(text-box.text, "5");
				}
			   }
			   Button {
				text: "6";
				clicked => {
					add_to_text_area(text-box.text, "6");
				}
			   }
			   Button {
				text: "*";
				clicked => {
					add_to_text_area(text-box.text, "*");
				}
			   }
			   Button {
				text: "/";
				clicked => {
					add_to_text_area(text-box.text, "/");
				}
			   }
		}

		//Row 3
		GridLayout {

			row: 3;

			Button {
				text: "7";
				clicked => {
					add_to_text_area(text-box.text, "7");
				}
			   }
			   Button {
				text: "8";
				clicked => {
					add_to_text_area(text-box.text, "8");
				}
			   }
			   Button {
				text: "9";
				clicked => {
					add_to_text_area(text-box.text, "9");
				}
			   }
			   Button {
				text: ".";
				clicked => {
					add_to_text_area(text-box.text, "+");
				}
			   }
			   Button {
				text: "Clear";
				clicked => {
					add_to_text_area(text-box.text, "Clear");
				}
			   }
		}

		GridLayout {

			row: 4;

			Button {
				width: 300px;
				text: "0";
				clicked => {
					add_to_text_area(text-box.text, "0");
				}
			   }
			   Button {
				width: 300px;
				text: "=";
				clicked => {
					add_to_text_area(text-box.text, "=");
				}
			   }
		}
	}
}